
version: '3'
services:
  app:
    container_name: license-service
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure         
    networks:
      - fullstack

volumes:
  api:
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge